services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    #volumes:
     # - .:/var/www # Mantener este volumen para el desarrollo local
    depends_on:
      - postgres_db # Cambiado a postgres_db para coincidir con el nombre del servicio
    networks:
      - laravel

  postgres_db: # Renombrado el servicio de 'postgres' a 'postgres_db' para mayor claridad y consistencia
    image: postgres:15 # Recomiendo usar una versión específica y más reciente si es posible, como 15 o 16. La 13 está bien, pero la 15 es más actual.
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: poligran2025
      POSTGRES_DB: z_camiseta
    volumes:
      - db_data:/var/lib/postgresql/data # ¡CAMBIO CLAVE AQUÍ! Usando un volumen con nombre
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

# ¡NUEVA SECCIÓN! Definición de los volúmenes con nombre
volumes:
  db_data: # Define el volumen con nombre 'db_data'