
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:13
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: poligran2025
      POSTGRES_DB: z_camiseta
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
