name: Laravel CI

on:
  push:
    branches: [ feat/test ]
  pull_request:
    branches: [ feat/test ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: poligran2025
          POSTGRES_DB: z_camiseta

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker compose version

      - name: Build and start containers
        run: docker compose up -d --build

      - name: Wait for Postgres to be ready
        run: |
          echo "Waiting for Postgres..."
          sleep 10

      - name: Run migrations
        run: |
          docker compose exec -T laravel-app cp .env-example .env
          docker compose exec -T laravel-app php artisan key:generate
          docker compose exec -T laravel-app php artisan migrate:fresh --seed --env=testing --force

      - name: Run tests
        run: docker compose exec -T laravel-app php artisan test --env=testing

